name: Build crosstool-ng for linux-amd64

on:
  push:
    paths:
      - '.github/workflows/linux-amd64.yml'
  workflow_dispatch:

env:
  CROSSTOOL_NG_TAG: crosstool-ng-1.25.0

permissions:
  contents: write

concurrency:
  group: linux-amd64
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          repository: crosstool-ng/crosstool-ng
          ref: ${{ env.CROSSTOOL_NG_TAG }}

      - name: Install dependencies
        run: |
          sudo apt install -y help2man libtool-bin

      - name: Build crosstool-ng
        run: |
          ./bootstrap
          ./configure --prefix=/usr
          make LDFLAGS="-all-static"
          make DESTDIR="$(pwd)/root" install
          tar -cvJf "${CROSSTOOL_NG_TAG}-linux-amd64.tar.xz" -C root .
          sha512sum "${CROSSTOOL_NG_TAG}-linux-amd64.tar.xz" > "${CROSSTOOL_NG_TAG}-linux-amd64.tar.xz.sha512"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: crosstool-ng-linux-amd64
          path: "${{ env.CROSSTOOL_NG_TAG }}-linux-amd64.tar.xz*"

  deploy:
    environment: releases
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: crosstool-ng-linux-amd64

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.CROSSTOOL_NG_TAG }}-linux-amd64.tar.xz*"
          tag: ${{ env.CROSSTOOL_NG_TAG }}
          commit: ${{ github.sha }}
          allowUpdates: true
          removeArtifacts: true
