name: Build crosstool-ng for linux-amd64

on:
  push:
    paths:
      - '.github/workflows/linux-amd64.yml'
  workflow_dispatch:

env:
  CROSSTOOL_NG_REF: 3020aca6bb00e1d0a1cef3ab6d28b578c7df6520

permissions:
  contents: write

concurrency:
  group: linux-amd64
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          repository: crosstool-ng/crosstool-ng
          ref: ${{ env.CROSSTOOL_NG_REF }}
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt install -y help2man libtool-bin

      - name: Get tarball name
        id: name
        run: |
          if [[ ${CROSSTOOL_NG_REF} = crostool-ng-* ]]; then
            echo "::set-output name=name::${CROSSTOOL_NG_REF}"
          else
            echo "::set-output name=name::$(git describe --abbrev=4 HEAD | sed -e 's/\([0-9]\)-/\1./' -e 's/-g/-/')"
          fi

      - name: Store tarball name
        run: |
          echo "${{ steps.name.outputs.name }}" > P

      - name: Build crosstool-ng
        run: |
          ./bootstrap
          ./configure --prefix=/usr
          make LDFLAGS="-all-static"
          make DESTDIR="$(pwd)/root" install
          tar -cvJf "${{ steps.name.outputs.name }}-linux-amd64.tar.xz" -C root .
          sha512sum "${{ steps.name.outputs.name }}-linux-amd64.tar.xz" > "${{ steps.name.outputs.name }}-linux-amd64.tar.xz.sha512"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: crosstool-ng-linux-amd64
          path: |
            ${{ steps.name.outputs.name }}-linux-amd64.tar.xz*
            P

  deploy:
    environment: releases
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: crosstool-ng-linux-amd64

      - name: Get tarball name
        id: name
        run: echo "::set-output name=name::$(cat P)"

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ steps.name.outputs.name }}-linux-amd64.tar.xz*"
          tag: ${{ steps.name.outputs.name }}
          commit: ${{ github.sha }}
          allowUpdates: true
          removeArtifacts: true
